# This job will run helm install to add the nesecearry services to a 
# target migration cluster.
# Requirements:
#   - this job must run with a service account that has admin permissions to 
#     be able create namespaces, resources in them, and so on.
# Usage:
#   Add this manifest to the 'custom manifest' section in the assisted installer 
#   wizard, or apply on a running cluster (see the Requirements section)
#   After the job runs a few new resources should apear, mainly MTV operator on
#   openshift-mtv namespace, and mtv-:init web application.
#   Navigate to https://mtv-init.apps.$clustername.$cluster-domain to start 
#   the provider configuration for MTV
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-post-cluster-installations
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6   
  template:         
    metadata:
      name: migration-post-cluster
    spec:
      containers:
      - name: migration-post-cluster
        image: registry.access.redhat.com/ubi9/ubi-minimal
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -o errexit

            ARCH=""
            case "$(arch)" in
                x86_64)
                    ARCH=amd64
                    ;;
                *)
                    echo "Architecture $(arch) is missing from the case match"
                    exit 1
                    ;;
            esac

            echo "Architecture is ${ARCH}"

            mkdir /tmp/migration-cluster-day2
            cd /tmp/migration-cluster-day2
            curl -sLo helm https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/helm/3.14.4/helm-linux-$ARCH
            chmod +x helm
            echo "Downloaded helm"

            ./helm install --repository-cache=$(pwd) migration-cluster-day2 https://github.com/rgolangh/migration-cluster-day2/releases/download/migration-cluster-day2-0.0.4/migration-cluster-day2-0.0.4.tgz 

            ./helm list
            echo sleep 20 && sleep 20
            ./helm list
            echo sleep 20 && sleep 20
            ./helm list
      restartPolicy: OnFailure    
