---
# pvc for the image registry for RWO - used with LVM storage backend
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-storage 
  namespace: openshift-image-registry 
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      # we require the image registry for building the vddk image, we don't need more than 
      # 50Gi at the moment
      storage: 50Gi

---
# changes to the image registry config resouce
#oc patch config.Imageregistry.operator.openshift.io/cluster --type=merge -p '{"spec":{"storage":{"pvc":{"claim":"image-registry-storage"}}}}'
---
