---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.lvmstorageOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-storage-operator-group
  namespace: {{ .Values.lvmstorageOperator.subscription.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.lvmstorageOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator 
  namespace: {{ .Values.lvmstorageOperator.subscription.namespace }}
spec:
  channel: {{ .Values.lvmstorageOperator.subscription.channel }}
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
---
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  finalizers:
  - lvmcluster.topolvm.io
  generation: 1
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - fstype: xfs
      name: vg1
      thinPoolConfig:
        chunkSizeCalculationPolicy: Static
        name: thin-pool-1
        overprovisionRatio: 10
        sizePercent: 90

