---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mtvOperator.subscription.namespace }}
  # prevent the namespace deletion because in some sceneraious the namespace
  # is not removed and stays in terminating state.
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{ .Values.mtvOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtv-operator
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.mtvOperator.subscription.channel }}
  installPlanApproval: Automatic
  name: mtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  feature_ui_plugin: "true"
  feature_validation: "true"
  feature_volume_populator: "true"
---
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: vmware-provider
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  labels:
    app: mtv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  type: vsphere
  url: "https://vcenter.example.com/sdk"
  secret:
    name: vmware-credentials
    namespace: {{ .Values.mtvOperator.subscription.namespace }}
  settings:
    vddkInitImage: image-registry.openshift-image-registry.svc:5000/{{ .Values.mtvOperator.subscription.namespace }}/vddk:latest
---
apiVersion: v1
kind: Secret
metadata:
  name: vmware-credentials
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---

