---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mtvOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mtv-operator-group
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.mtvOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtv-operator 
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
spec:
  channel: {{ .Values.mtvOperator.subscription.channel }}
  installPlanApproval: Automatic
  name: mtv-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
---
kind: ForkliftController
apiVersion: forklift.konveyor.io/v1beta1
metadata:
  name: forklift-controller
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
spec:
  feature_ui_plugin: 'true'
  feature_validation: 'true'
  feature_volume_populator: 'true'

---
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: vmware-provider
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  labels:
    app: mtv
spec:
  type: vsphere
  url: "https://vcenter.example.com/sdk"
  secret:
    name: vmware-credentials
    namespace: {{ .Values.mtvOperator.subscription.namespace }}
  settings:
    vddkInitImage: image-registry.openshift-image-registry.svc:5000/mtv-operator/vddk:latest 
---
apiVersion: v1
kind: Secret
metadata:
  name: vmware-credentials
  namespace: {{ .Values.mtvOperator.subscription.namespace }}

