---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nmstateOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nmstate-operator-group
  namespace: {{ .Values.nmstateOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{ .Values.nmstateOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nmstate-operator 
  namespace: {{ .Values.nmstateOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.nmstateOperator.subscription.channel }}
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
---
# don't try to create nmstate because argocd doesn't create cluster-scooped resources out of the box
# apiVersion: nmstate.io/v1
# kind: NMState
# metadata:
#   name: nmstate
#   namespace: {{ .Values.nmstateOperator.subscription.namespace }}
#   labels: {{ include "migration-cluster-day2.labels" . | nindent 4 }}
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# spec: {}

