---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nmstateOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nmstate-operator-group
  namespace: {{ .Values.nmstateOperator.subscription.namespace }}
  annotations:
spec:
  argocd.argoproj.io/sync-wave: "1"
  targetNamespaces:
    - {{ .Values.nmstateOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nmstate-operator 
  namespace: {{ .Values.nmstateOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.nmstateOperator.subscription.channel }}
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
---
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: nmstate
  namespace: {{ .Values.nmstateOperator.subscription.namespace }}
  labels: {{ include "migration-cluster-day2.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}

